### ISSUE TITLE
Add repository defaults

### ISSUE THREAD

**Issue by matthewfeickert** [j-s-ashley/build_tools_sandbox#1]
Even for test projects it is good practice to have some repository structure and defaults. GitHub helps you with this when creating a project by including options to generate a `README`, `LICENSE`, and `.gitignore` file at repository creation.

As a small exercise:

* Add a README to the project.
* Add a LICENSE to the project (https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)
   - You can choose what LICENSE you want (c.f. https://choosealicense.com/) though selecting MIT if in doubt is probably fine.
* Add a Python .gitignore to the project (can just download and rename https://github.com/github/gitignore/blob/main/Python.gitignore)
* Move the project files under `sk_b_c_example_swig/` to the top level directory to make it easier for a CI based workflow in the future

Do this in a typical [PR based workflow](https://docs.github.com/en/get-started/using-github/github-flow) and use a [GitHub closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to automatically close this Issue when the PR gets merged.

**Comment by j-s-ashley** [comment]
> You can choose what LICENSE you want (c.f. https://choosealicense.com/) though selecting MIT if in doubt is probably fine.

Since [the example's repository uses the Apache license](https://github.com/scikit-build/scikit-build-core/blob/main/LICENSE), that's what I used here.

**Comment by matthewfeickert** [comment]
> Since [the example's repository uses the Apache license](https://github.com/scikit-build/scikit-build-core/blob/main/LICENSE), that's what I used here.

That's fine. Though as you start making edits and changes to the files or adding new ones for testing you should probably add a LICENSE file that is your own and not copyrighted to @henryiii

https://github.com/j-s-ashley/build_tools_sandbox/blob/273bf85257dafb8f3547317e869d4dc5484125e4/LICENSE#L190

Also to automatically clean up the feature branches on the repo after you merge them in, you can go into [the repo settings](https://github.com/j-s-ashley/build_tools_sandbox/settings) and then select the "Automatically delete head branches" option, which looks like this:

![image](https://github.com/j-s-ashley/build_tools_sandbox/assets/5142394/76319fa8-dec2-41b2-8366-6e967fda91f9)

You may already know this, but to locally remove a branch from your repository, you can use [`git branch -d <branch name>`](https://git-scm.com/docs/git-branch#Documentation/git-branch.txt--d) and you may need to use `git branch -D` if you do a squash and merge, which is pretty common.
