### ISSUE TITLE
Add pre-commit hooks and pre-commit.ci

### ISSUE THREAD

**Issue by matthewfeickert** [j-s-ashley/build_tools_sandbox#4]
Add [`pre-commit` hooks](https://pre-commit.com/) to the project by creating and then adding a `.pre-commit-config.yaml` file in a PR.

Additionally integrate https://pre-commit.ci/ with your GitHub account and enable it for this repository.

c.f. the [`pre-commit` section in the Scientific Python Developer Guide](https://learn.scientific-python.org/development/guides/style/#pre-commit) for more information.

**Comment by j-s-ashley** [comment]
Resolved via PR #8
